# Stage 1: Builder
FROM python:3.11-slim as builder
WORKDIR /app
RUN pip install --no-cache-dir poetry poetry-plugin-export
COPY pyproject.toml poetry.lock* ./
RUN poetry export -f requirements.txt --output requirements.txt --without-hashes

# Stage 2: Runtime
FROM python:3.11-slim
WORKDIR /app
COPY --from=builder /app/requirements.txt .

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# EXPLICIT INSTALL: Guaranteeing the backend dependencies exist
RUN pip install --no-cache-dir -r requirements.txt fastapi uvicorn pydantic xgboost pandas joblib scikit-learn==1.4.0 shap dowhy great_expectations python-multipart pyarrow fastparquet

COPY src ./src
COPY models ./models
COPY artifacts ./artifacts
COPY data ./data

EXPOSE 8000
# Bypass Linux $PATH issues by running as a Python module
CMD ["python", "-m", "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]