services:
  - type: web
    name: neuralretail-api
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile.api
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: LOG_LEVEL
        value: INFO
      - key: MODEL_PATH
        value: ./models

  - type: web
    name: neuralretail-app
    env: docker
    region: oregon
    plan: starter
    dockerfilePath: ./Dockerfile.app
    dockerContext: .
    healthCheckPath: /_stcore/health
    envVars:
      - key: API_BASE_URL
        value: https://neuralretail-api.onrender.com
      - key: LOG_LEVEL
        value: INFO
