credentials:
  usernames:
    admin:
      email: [EMAIL_ADDRESS]
      name: System Administrator
      password: $2b$12$eDiKPE3DjP4eumK0ibFolOPMCRMRPgkwDv7UOLjfY0mHr7hzCR4cm # abc
      role: admin
    executive:
      email: exec@neuralretail.ai
      name: Executive User
      password: $2b$12$QPsNXt9YpRJapW1QI.vlS.SonFepXEvlj.RZkAsxpF7BamTEs5MQC # def
      role: executive
cookie:
  expiry_days: 30
  key: neural_retail_auth
  name: neural_retail_cookie
pre-authorized:
  emails:
    - admin@neuralretail.ai
